Website/web-pi/webapp/__init__.py
import os
from flask import Flask
from flask_login import LoginManager


app = Flask(__name__)

#############################################################################
############ CONFIGURATIONS (CAN BE SEPARATE CONFIG.PY FILE) ###############
###########################################################################

app.config['SECRET_KEY'] = 'catalinsecretkey'

#################################
### DATABASE SETUPS ############
###############################

basedir = os.path.abspath(os.path.dirname(__file__))


###########################
#### LOGIN CONFIGS #######
#########################

login_manager = LoginManager()

# We can now pass in our app to the login manager
login_manager.init_app(app)

# Tell users what view to go to when they need to login.
login_manager.login_view = "core.login"


###########################
#### BLUEPRINT CONFIGS #######
#########################

# Import these at the top if you want
# We've imported them here for easy reference
from webapp.core.views import core
from webapp.flow.views import flow

# Register the apps
app.register_blueprint(core)
app.register_blueprint(flow)

Website/web-pi/webapp/core/views.py
from flask import render_template,request,Blueprint, redirect, request, url_for
from webapp import login_manager

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view.
    '''
    return render_template('index.html')

@core.route('/info')
def info():
    '''
    Info page.
    '''
    return render_template('features.html')

class User:
    pass

@core.route('/login', methods=['GET', 'POST'])
def login():
    """
    LogIn page.
    """
    error = None

    if request.method == 'POST':

        if request.form['username'] != 'tbchip' or request.form['password'] != 'catalin':
            error = 'Invalid Credentials. Please try again.'
        else:
            load_user(User())
            return redirect(url_for('flow.flow_page'))

    return render_template('login.html', error=error)

@login_manager.user_loader
def load_user(user):
    # print(user)
    return user

Website/web-pi/webapp/flow/views.py
from flask import render_template,request,Blueprint
from flask_login import login_required
from webapp import login_manager
import paho.mqtt.client as mqtt
import json
import ssl


flow = Blueprint('flow',__name__)

BROKER_ADDRESS="test.mosquitto.org"
N=8884

client = mqtt.Client()
client.tls_set(ca_certs="mosquitto.org.crt",certfile="client.crt",keyfile="client.key",tls_version=ssl.PROTOCOL_TLSv1_2)
print("Transmission:")
print(client.connect(BROKER_ADDRESS,port=N))
client.subscribe("IC.embedded/TBChip/#")
data = {'temperature':0.0, 'warnings': "..."}


    #return render_template('flow.html', data=data)



# TODO: require authentification from login_manager
@flow.route('/flow')
# @login_required
def flow_page():
    '''
    This is the data flow.
    '''
    def on_message(client, userdata, message):
        global data
        datacpy = message.payload
        data = json.loads(datacpy)

        print(data)
    # If start pushed
    client.on_message = on_message
    client.loop_start()

    # If stop pushed
    # client.end_loop()

    return render_template('flow.html', data=data)
"""
@flow.route('/receiver')
def receiver():"""

"""
    text = request.args.get('jsdata')
    global data
    return render_template('suggestions.html', data=data)
"""

Website/web-pi/webapp/templates/features.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Features - Brand</title>
    <link rel="stylesheet" href="{{url_for('static', filename='assets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/fonts/simple-line-icons.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/smoothproducts.css')}}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top  clean-navbar" style="background-color: rgba(210, 210, 210, 0.3);">
        <div class="container"><a class="navbar-brand logo" href="{{url_for('core.index')}}"><img src="{{url_for('static', filename= 'assets/img/avatars/logo.png')}}" height="40" width="110" alt="logo"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="{{url_for('core.index')}}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.info')}}">Features</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.login')}}">Login</a></li>

                </ul>
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </nav>
    <main class="page">
        <section class="clean-block features dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Injury prevention</h2>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-6"><img class="img-thumbnail" src="{{url_for('static', filename='assets/img/scenery/Capture8.png')}}"></div>
                    <div class="col-md-6">
                        <div class="getting-started-info">
                            <p><br>The number one reason&nbsp;keeping&nbsp;people out of the gym is&nbsp;an&nbsp;injury. The&nbsp;top three occurring&nbsp;injuries&nbsp;in&nbsp;the gym are&nbsp;the&nbsp;lower back, the shoulders and the knees.&nbsp;All of
                                which can be contributed to improper form when doing the most likely causing exercises: squats, deadlifts and over-head press.&nbsp;Strategically located flex sensors
                                will be able to record and relay any points throughout a set where your technique was slacking.&nbsp;Injury prevention would be the most important thing&nbsp;a personal trainer&nbsp;would be focused on.&nbsp;<br><br></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="clean-block features">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Calorie burn rate</h2>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="getting-started-info">
                            <p style="text-align:right"><br>Several studies&nbsp;also show there is a clear optimal temperature to exercises at both for safety concerns and maximum calorie burn.&nbsp;The essential body temperature for training is around 37.5 degrees Celsius.&nbsp;Muscles and ligaments that aren’t warmed
                                up properly are a greater risk of tearing&nbsp;and a higher calorie burn is more beneficial to fat loss. Thermopile sensors can record your body temperature throughout a workout and remind you when you have entered that
                                sweet spot temperature.&nbsp;<br><br></p>
                        </div>
                    </div>
                    <div class="col-md-6"><img class="img-thumbnail" src="{{url_for('static', filename='assets/img/scenery/Capture11.png')}}"></div>
                </div>
            </div>
        </section>
    </main>
    <footer class="page-footer dark">
        <div class="footer-copyright">
            <p>© Form First 2021</p>
        </div>
    </footer>
    <script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{{url_for('static', filename='assets/js/smoothproducts.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/js/theme.js')}}"></script>
</body>

</html>

Website/web-pi/webapp/templates/flow.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="refresh" content="5" >
    <title>Data flow</title>
    <link rel="stylesheet" href="{{url_for('static', filename='assets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/fonts/simple-line-icons.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/smoothproducts.css')}}">
    <!-- <script src="{{url_for('static', filename='assets/js/own.js')}}"></script> -->
</head>

<body>
  <nav class="navbar navbar-light navbar-expand-lg fixed-top  clean-navbar" style="background-color: rgba(210, 210, 210, 0.3);">
      <div class="container"><a class="navbar-brand logo" href="{{url_for('core.index')}}"><img src="{{url_for('static', filename= 'assets/img/avatars/logo.png')}}" height="40" width="110" alt="logo"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse"
              id="navcol-1">
              <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item" role="presentation"><a class="nav-link active" href="{{url_for('core.index')}}">Home</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.info')}}">Features</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.login')}}">Login</a></li>

              </ul>
              <ul class="nav navbar-nav"></ul>
          </div>
      </div>
  </nav>
    <main class="page contact-us-page">
        <section class="clean-block clean-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Training status</h2>

                </div>
                <div class="row justify-content-center">
                  <div class="col-md-5"
                    <label>Temperature</label><textarea class="form-control" rows="6" cols="6" id="dataTemp">{{data['temperature']}}</textarea>
                    <label>Message</label><textarea class="form-control" rows="6" cols="6" id="dataFlow">{{data['warnings'][0]}} {{data['warnings'][1]}} {{data['warnings'][2]}} {{data['warnings'][3]}}</textarea>
                  <!--  <button class="btn btn-success btn-block" type="submit" onclick="print_data=false;">Start</button>
                <!--<input id="start"> Start
               <input type="text" id="start"> Start </input>
                </input>
                    <button class="btn btn-success btn-block" type="submit" onclick="print_data=false;">Stop</button>-->
                  </div>
                </div>
                </div>
        </section>
    </main>
    <footer class="page-footer dark">
        <div class="footer-copyright">
            <p>© Form First 2021</p>
        </div>
    </footer>
    <script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <!--<script type="text/javascript">

    $("#start").keyup(function(){
    var text = $(this).val();
    console.log("Started reuest");
    $.ajax({
            url: "/receiver",
            type: "get",
            data: {jsdata: text},
            success: function(response) {
              console.log(response);
              $("#dataFlow").html(response);
            },
            error: function(xhr) {
              console.log("Error");
              console.log(xhr);
            }
          });
      });
    </script>--->
    <script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{{url_for('static', filename='assets/js/smoothproducts.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/js/theme.js')}}"></script>

</body>

</html>

Website/web-pi/webapp/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Form First</title>
    <link rel="stylesheet" href="{{url_for('static', filename='assets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/fonts/simple-line-icons.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/smoothproducts.css')}}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top  clean-navbar" style="background-color: rgba(210, 210, 210, 0.3);">
        <div class="container"><a class="navbar-brand logo" href="{{url_for('core.index')}}"><img src="{{url_for('static', filename= 'assets/img/avatars/logo.png')}}" height="40" width="110" alt="logo"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="{{url_for('core.index')}}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.info')}}">Features</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.login')}}">Login</a></li>

                </ul>
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </nav>
    <main class="page landing-page">
        <section class="clean-hero clean-block" style="background-image:url( {{url_for('static', filename = 'assets/img/scenery/Capture1.png/') }} );color:rgba(30, 30, 30, 0.85);">
            <div class="text">
                <h1>Optimise your workout</h1>
                <p><br>Form First is an IOT device that&nbsp;brings the expertise of personal trainers to your fingertips.&nbsp;Through immediate and accurate feedback,&nbsp;Form&nbsp;first&nbsp;can optimise your workouts and focuses on injury prevention.&nbsp;<br></p>
                    <a href="{{url_for('core.info')}}" class="btn btn-outline-light btn-lg" role="button">Learn More</a>
            </div>
        </section>
        <section class="clean-block clean-info dark">
            <div class="container">
                <div class="block-heading">


                </div>
                <div class="row align-items-center">
                    <div class="col-md-6">
                      <h2 class="text-success" style="text-align: center;margin: 40px;">Marketing promotion</h2>
                      <iframe allowfullscreen="" frameborder="0" width="500" height="450" src="https://www.youtube.com/embed/LU8dyoMX1k8?autoplay=1&amp;mute=1"></iframe></div>
                    <div class="col-md-6">
                      <h2 class="text-success" style="text-align: center;margin: 40px;">Demonstration video</h2>
                      <iframe allowfullscreen="" frameborder="0" width="500" height="450" src="https://www.youtube.com/embed/7Ggg3H4ssuA?autoplay=1&amp;mute=1"></iframe></div>
                </div>
            </div>
        </section>
        <section class="clean-block features">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Features</h2>
                    <!--<p>Some special features are included in our product:</p>-->
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-5 feature-box"><i class="icon-star icon" style="color:rgb(0, 204, 0)"></i>
                        <h4>Integratable</h4>
                        <p>Form first is compatible with multiple joints that are prone to injury, including for example the wrist, shoulders, lower back and knees. The device is also integratable with commonly used gym equipment such as wrist straps, lifting belts, and knee sleeves. </p>
                    </div>
                    <div class="col-md-5 feature-box"><i class="icon-pencil icon" style="color:rgb(0, 204, 0)"></i>
                        <h4>Lightweight</h4>
                        <p>Along with being long lasting and durable, the Form First device is extremely lightweight and doesn’t interfere with your workouts.</p>
                    </div>
                    <div class="col-md-5 feature-box"><i class="icon-screen-smartphone icon " style="color:rgb(0, 204, 0)"></i>
                        <h4>Easy to user interface</h4>
                        <p>Communication between the device and website/application is fast and reliable. It is capable of providing immediate and accurate feedback. </p>
                    </div>
                    <div class="col-md-5 feature-box"><i class="icon-refresh icon" style="color:rgb(0, 204, 0)"></i>
                        <h4>Fast and wireless connection</h4>
                        <p>User friendly and ergonomically designed interface with easy to access data on your workouts. Data is processed, formatted and clearly presented to the customer. </p>
                    </div>
                </div>
            </div>
        </section>
        <section class="clean-block features dark">
            <div class="container">
                <div class="block-heading"></div>
                <div class="row align-items-center">
                    <div class="col-md-6"><img class="img-thumbnail" src="{{url_for('static', filename='assets/img/scenery/Capture2.png')}}"></div>
                    <div class="col-md-6">
                        <div class="getting-started-info">
                            <h3 class="text-success" style="text-align:center">Competition</h3>
                            <p style="text-align:center"><br>Unlike Form First, there are dozens of fitness applications available all offer the same service: personalised workouts and food plans. Gym maniacs, exercise enthusiasts and new goers are bombarded with the same overload
                                of information. Form First avoids this heavily saturated market area of the fitness industry. It instead targets a gaping whole in the market with very few competitors.&nbsp;<br><br></p>
                        </div>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="getting-started-info">
                            <h3 class="text-success" style="text-align: center;margin: 40px;">Demand Reasoning</h3>
                            <p style="text-align:center">The demand for a product like this has shot up since&nbsp;the&nbsp;beginning&nbsp;of the pandemic due to the closure of gyms. Vast&nbsp;increasing&nbsp;numbers of the public have been buying up&nbsp;their own gym equipment&nbsp;and
                                are&nbsp;working out&nbsp;at home.&nbsp;The proof&nbsp;of such&nbsp;dramatic increase of home workouts is clear from the price spike in&nbsp;gym&nbsp;equipment&nbsp;of&nbsp;over 5,800% since March 2020.1&nbsp;Training at
                                home, however, comes with its downsides. Unfortunately, from&nbsp;a lack of hand on&nbsp;guidance&nbsp;from licensed personal trainers,&nbsp;inexperienced weight lifters&nbsp;will begin to&nbsp;develop&nbsp;many injuries&nbsp;from
                                incorrect technique&nbsp;during these home workouts.<br><br></p>
                        </div>
                    </div>
                    <div class="col-md-6"><img class="img-thumbnail" src="{{url_for('static', filename='assets/img/scenery/Capture10.png')}}"></div>
                </div>
            </div>
        </section>
        <section class="clean-block about-us">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Meet the team</h2>
                    <p>The concept of Form First was carefully created by our team of ingenious and driven engineers. It is designed according to the needs and desires of the users.</p>
                </div>
                <div class="row justify-content-center">
                    <div class="col-sm-6 col-lg-4">
                        <div class="card clean-card text-center"><img class="card-img-top w-100 d-block" src="{{url_for('static', filename='assets/img/avatars/avatar2.png')}}">
                            <div class="card-body info">
                                <h4 class="card-title">Catalin Craciun</h4>
                                <p class="card-text">Head of Web Development</p>
                                <div class="icons"><a href="#"><i class="icon-social-facebook" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-instagram" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-twitter" style="color:rgb(0, 204, 0)"></i></a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4">
                        <div class="card clean-card text-center"><img class="card-img-top w-100 d-block" src="{{url_for('static', filename='assets/img/avatars/avatar1.png')}}">
                            <div class="card-body info">
                                <h4 class="card-title">Alex Oprea</h4>
                                <p class="card-text">Head of Hardware Systems</p>
                                <div class="icons"><a href="#"><i class="icon-social-facebook" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-instagram" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-twitter" style="color:rgb(0, 204, 0)"></i></a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-4">
                        <div class="card clean-card text-center"><img class="card-img-top w-100 d-block" src="{{url_for('static', filename='assets/img/avatars/avatar3.png')}}">
                            <div class="card-body info">
                                <h4 class="card-title">Gordon Thompson</h4>
                                <p class="card-text">Head of MQTT and Marketing</p>
                                <div class="icons"><a href="#"><i class="icon-social-facebook" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-instagram" style="color:rgb(0, 204, 0)"></i></a><a href="#"><i class="icon-social-twitter" style="color:rgb(0, 204, 0)"></i></a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer class="page-footer dark">
        <div class="footer-copyright">
            <p>© Form First 2021</p>
        </div>
    </footer>
    <script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{{url_for('static', filename='assets/js/smoothproducts.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/js/theme.js')}}"></script>
</body>

</html>

Website/web-pi/webapp/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login</title>
    <link rel="stylesheet" href="{{url_for('static', filename='assets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/fonts/simple-line-icons.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/smoothproducts.css')}}">
</head>

<body>
  <nav class="navbar navbar-light navbar-expand-lg fixed-top  clean-navbar" style="background-color: rgba(210, 210, 210, 0.3);">
      <div class="container"><a class="navbar-brand logo" href="{{url_for('core.index')}}"><img src="{{url_for('static', filename= 'assets/img/avatars/logo.png')}}" height="40" width="110" alt="logo"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse"
              id="navcol-1">
              <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item" role="presentation"><a class="nav-link active" href="{{url_for('core.index')}}">Home</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.info')}}">Features</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('core.login')}}">Login</a></li>

              </ul>
              <ul class="nav navbar-nav"></ul>
          </div>
      </div>
  </nav>
    <main class="page login-page">
        <section class="clean-block clean-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-success">Log In</h2>
                    <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>-->
                </div>
                <form method="POST">
                    <div class="form-group"><label for="email">User</label><input class="form-control item" name="username" value="{{request.form.username }}" ></div>
                    <div class="form-group"><label for="password">Password</label><input class="form-control" type="password" name="password" value="{{request.form.password}}"></div>
                    <div class="form-group">
                    </div><button class="btn btn-success btn-block" type="submit">Log In</button></form>
                    {% if error %}
                    <p class="error"><strong>Error:</strong> {{ error }}
                    {% endif %}
            </div>
        </section>
    </main>
    <footer class="page-footer dark">
        <div class="footer-copyright">
            <p>© Form First 2021</p>
        </div>
    </footer>
    <script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{{url_for('static', filename='assets/js/smoothproducts.min.js')}}"></script>
    <script src="{{url_for('static', filename='assets/js/theme.js')}}"></script>
</body>

</html>